[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "mrc"
version = "1.0.5"
dependencies = [
    "pypulseq",
    "numpy",
    "scipy",
    "pyserial"
]

[tool.setuptools.packages.find]
where = ["."]
